url: https://hearts-workshop.github.io
baseurl: /

# Site settings
title: HEARTS Workshop
email: aqzhang@andrew.cmu.edu
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Team names, titles and social links
people:
- name: Alice Qian
  pic: 1
  position: Carnegie Mellon University

- name: Srravya Chandhiramowuli
  pic: 2
  position: Univeresity of Edinburgh

- name: Laura Dabbish
  pic: 3
  position: Carnegie Mellon University

- name: Hong Shen
  pic: 4
  position: Carnegie Mellon University

- name: Alex S. Taylor
  pic: 5
  position: University of Edinburgh

- name: Ding Wang
  pic: 6
  position: Google

- name: Theodora Skeadas
  pic: 7
  position: Humane Intelligence

- name: Bolor-Erdene Jagdagdorj
  pic: 8
  position: Microsoft

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket 
#     url: http://bitbucket.org/jekyll
#   - title: github
    # url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty